
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
@SuppressWarnings("serial")
public class offline extends JFrame implements ActionListener
{
JPanel p1,p2,p3,p4;
Container c;
JFrame jf;
JButton b1,b2,b3,b4,b5,b6,b7,b8,b9,b10;
Color cc;
int count=0;
int a1,a2,a3,a4,a5,a6,a7,a8;
public offline()
{
jf=new JFrame("Tic-Tac toe");
c=jf.getContentPane();
c.setLayout(null);
c.setBackground(Color.black);
JPanel jp=new JPanel();
jp.setLayout(null);
jp.setBackground(Color.gray);
jp.setBounds(50,50,550,450);
p1=new JPanel();
p1.setBackground(Color.yellow);
p1.setBounds(150,200,300,5);
c.add(p1);
p2=new JPanel();
p2.setBackground(Color.yellow);
p2.setBounds(150,300,300,5);
c.add(p2);

p3=new JPanel();
p3.setBackground(Color.yellow);
p3.setBounds(250,100,5,300);
c.add(p3);

p4=new JPanel();
p4.setBackground(Color.yellow);
p4.setBounds(350,100,5,300);
c.add(p4);
c.add(jp);
b1=new JButton("");
b2=new JButton("");
b3=new JButton("");
b4=new JButton("");
b5=new JButton("");
b6=new JButton("");
b7=new JButton("");
b8=new JButton("");
b9=new JButton("");
cc=b1.getBackground();
b1.addActionListener(this);
b2.addActionListener(this);
b3.addActionListener(this);
b4.addActionListener(this);
b5.addActionListener(this);
b6.addActionListener(this);
b7.addActionListener(this);
b8.addActionListener(this);
b9.addActionListener(this);
b1.setBounds(140,90,50,50);
jp.add(b1);
b2.setBounds(230,90,50,50);
jp.add(b2);
b3.setBounds(320,90,50,50);
jp.add(b3);

b7.setBounds(140,280,50,50);
jp.add(b7);
b8.setBounds(230,280,50,50);
jp.add(b8);
b9.setBounds(320,280,50,50);
jp.add(b9);

b4.setBounds(140,180,50,50);
jp.add(b4);
b5.setBounds(230,180,50,50);
jp.add(b5);
b6.setBounds(320,180,50,50);
jp.add(b6);
b10=new JButton("New");
b10.addActionListener(this);
b10.setBounds(350,400,80,30);
jp.add(b10);


jf.setVisible(true);
jf.setSize(700,600);
}
public void actionPerformed(ActionEvent ae)
{
if(ae.getSource()==b10)
{
count=0;
a1=0;
a2=0;
a3=0;
a4=0;
a5=0;
a6=0;
a7=0;
a8=0;
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


if(ae.getSource()==b1)
{
if(b1.getText().equals(""))
{
b1.setText("*");
b1.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b1.getText().equals("*")&&b2.getText().equals("*")&&b3.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("*")&&b5.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("*")&& b4.getText().equals("*")&&b7.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b2.getText().equals("")&&count==0)
{
b2.setText("0");
b2.setBackground(Color.green);
count++;
}
if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if((b4.getText().equals(""))&&(count==0))
{
b4.setText("0");
b4.setBackground(Color.green);
count+=1;
}


if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if((b5.getText().equals(""))&&(count==0))
{
b5.setText("0");
b5.setBackground(Color.green);
count+=1;

}
if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
count=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}




}

if(ae.getSource()==b2)
{
if(b2.getText().equals(""))
{
b2.setText("*");
b2.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b2.getText().equals("*")&&b3.getText().equals("*")&&b1.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("*")&&b5.getText().equals("*")&&b8.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b3.getText().equals("")&&a1==0)
{
b3.setText("0");
b3.setBackground(Color.green);
a1=1;
}

if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("0")&&b3.getText().equals("0")&&b7.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("")&&a1==0)
{
b1.setText("0");
b1.setBackground(Color.green);
a1=1;
}


if(b1.getText().equals("0")&&b2.getText().equals("0")&&b3.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&& b4.getText().equals("0")&&b7.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}

if(b5.getText().equals("")&&a1==0)
{
b5.setText("0");
b5.setBackground(Color.green);
a1=1;
}
if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a1=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


}

if(ae.getSource()==b3)
{
if(b3.getText().equals(""))
{
b3.setText("*");
b3.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b2.getText().equals("*")&&b3.getText().equals("*")&&b1.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("*")&&b3.getText().equals("*")&&b7.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("*")&&b3.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("")&&a2==0)
{
a2=1;
b6.setText("0");
b6.setBackground(Color.green);
}

if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b5.getText().equals("0")&&b4.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("")&&a2==0)
{
a2=1;
b5.setText("0");
b5.setBackground(Color.green);
}

if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b2.getText().equals("")&&a2==0)
{
b2.setText("0");
b2.setBackground(Color.green);
a2++;
}
if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a2=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}



}


if(ae.getSource()==b4)
{
if(b4.getText().equals(""))
{
b4.setText("*");
b4.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b1.getText().equals("*")&&b4.getText().equals("*")&&b7.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("*")&&b5.getText().equals("*")&&b6.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


if(b1.getText().equals("")&&a3==0)
{
b1.setText("0");
b1.setBackground(Color.green);
a3=1;
}


if(b1.getText().equals("0")&&b2.getText().equals("0")&&b3.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&& b4.getText().equals("0")&&b7.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}


if(b5.getText().equals("")&&a3==0)
{
a3=1;
b5.setText("0");
b5.setBackground(Color.green);
}

if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b7.getText().equals("")&&a3==0)
{
b7.setText("0");
b7.setBackground(Color.green);
a3=1;
}
if(b7.getText().equals("0")&&b3.getText().equals("0")&&b5.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a3=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

}

if(ae.getSource()==b5)
{
if(b5.getText().equals(""))
{
b5.setText("*");
b5.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}

if(b9.getText().equals("*")&&b5.getText().equals("*")&&b1.getText().equals("*"))
{

Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("*")&&b5.getText().equals("*")&&b8.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("*")&&b5.getText().equals("*")&&b6.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("*")&&b5.getText().equals("*")&&b7.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


if(b7.getText().equals("")&&a4==0)
{
b7.setText("0");
b7.setBackground(Color.green);
a4=1;
}
if(b7.getText().equals("0")&&b3.getText().equals("0")&&b5.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


if(b9.getText().equals("")&&a4==0)
{
b9.setText("0");
b9.setBackground(Color.green);
a4=1;
}
if(b3.getText().equals("0")&&b6.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}


if(b3.getText().equals("")&&a4==0)
{
b3.setText("0");
b3.setBackground(Color.green);
a4=1;
}

if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("0")&&b3.getText().equals("0")&&b7.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("")&&a4==0)
{
b1.setText("0");
a4=1;
b1.setBackground(Color.green);
}
if(b1.getText().equals("0")&&b2.getText().equals("0")&&b3.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}
if(b1.getText().equals("0")&& b4.getText().equals("0")&&b7.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);

}


if(b2.getText().equals("")&&a4==0)
{
b2.setText("0");
b2.setBackground(Color.green);
a4=1;
}
if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b6.getText().equals("")&&a4==0)
{
a4=1;
b6.setText("0");
b6.setBackground(Color.green);
}

if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b5.getText().equals("0")&&b4.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if((b4.getText().equals(""))&&(a4==0))
{
b4.setText("0");
b4.setBackground(Color.green);
a4=1;
}


if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b8.getText().equals("")&&a4==0)
{
a4=1;
b8.setText("0");

b8.setBackground(Color.green);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b8.getText().equals("0")&&b5.getText().equals("0"))
{
a4=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
}

if(ae.getSource()==b6)
{
if(b6.getText().equals(""))
{
b6.setText("*");
b6.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b6.getText().equals("*")&&b3.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("*")&&b5.getText().equals("*")&&b4.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("")&&a5==0)
{
b3.setText("0");
b3.setBackground(Color.green);
a5=1;
}

if(b2.getText().equals("0")&&b3.getText().equals("0")&&b1.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("0")&&b3.getText().equals("0")&&b7.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b5.getText().equals("")&&a5==0)
{
a5=1;
b5.setText("0");
b5.setBackground(Color.green);
}

if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b9.getText().equals("")&&a5==0)
{
b9.setText("0");
b9.setBackground(Color.green);
a5=1;
}
if(b3.getText().equals("0")&&b6.getText().equals("0")&&b9.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a5=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

}

if(ae.getSource()==b7)
{
if(b7.getText().equals(""))
{
b7.setText("*");
b7.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b7.getText().equals("*")&&b3.getText().equals("*")&&b5.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("*")&&b4.getText().equals("*")&&b7.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("*")&&b8.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if((b4.getText().equals(""))&&(a6==0))
{
b4.setText("0");
b4.setBackground(Color.green);
a6+=1;
}


if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if((b5.getText().equals(""))&&(a6==0))
{
b5.setText("0");
b5.setBackground(Color.green);
a6+=1;

}
if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b8.getText().equals("")&&a6==0)
{
a6++;
b8.setText("0");

b8.setBackground(Color.green);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b8.getText().equals("0")&&b5.getText().equals("0"))
{
a6=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

}

if(ae.getSource()==b8)
{
if(b8.getText().equals(""))
{
b8.setText("*");
b8.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b7.getText().equals("*")&&b8.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("*")&&b8.getText().equals("*")&&b5.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b9.getText().equals("")&&a7==0)
{
b9.setText("0");
b9.setBackground(Color.green);
a7=1;
}
if(b3.getText().equals("0")&&b6.getText().equals("0")&&b9.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b5.getText().equals("0")&&b9.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if((b5.getText().equals(""))&&(a7==0))
{
b5.setText("0");
b5.setBackground(Color.green);
a7+=1;

}
if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("")&&a7==0)
{
b7.setText("0");
b7.setBackground(Color.green);
a7=1;
}
if(b7.getText().equals("0")&&b3.getText().equals("0")&&b5.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("0")&&b4.getText().equals("0")&&b7.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a7=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}



}

if(ae.getSource()==b9)
{
if(b9.getText().equals(""))
{
b9.setText("*");
b9.setBackground(Color.red);
}
else
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"Already Reserved");
}
if(b3.getText().equals("*")&&b6.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b1.getText().equals("*")&&b5.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b7.getText().equals("*")&&b8.getText().equals("*")&&b9.getText().equals("*"))
{
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if((b5.getText().equals(""))&&a8==0)
{
b5.setText("0");
b5.setBackground(Color.green);
a8=1;

}
if(b9.getText().equals("0")&&b5.getText().equals("0")&&b1.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b5.getText().equals("0")&&b8.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b4.getText().equals("0")&&b5.getText().equals("0")&&b6.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b3.getText().equals("0")&&b5.getText().equals("0")&&b7.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}

if(b8.getText().equals("")&&a8==0)
{
a8=1;
b8.setText("0");

b8.setBackground(Color.green);
}
if(b7.getText().equals("0")&&b8.getText().equals("0")&&b9.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b2.getText().equals("0")&&b8.getText().equals("0")&&b5.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("")&&a8==0)
{
a8=1;
b6.setText("0");
b6.setBackground(Color.green);
}

if(b6.getText().equals("0")&&b3.getText().equals("0")&&b9.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You Won!!!");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}
if(b6.getText().equals("0")&&b5.getText().equals("0")&&b4.getText().equals("0"))
{
a8=0;
Toolkit.getDefaultToolkit().beep();
JOptionPane.showMessageDialog(null,"You lost the game");
b1.setText("");
b1.setBackground(cc);
b2.setText("");
b2.setBackground(cc);
b3.setText("");
b3.setBackground(cc);
b4.setText("");
b4.setBackground(cc);
b5.setText("");
b5.setBackground(cc);
b6.setText("");
b6.setBackground(cc);
b7.setText("");
b7.setBackground(cc);
b8.setText("");
b8.setBackground(cc);
b9.setText("");
b9.setBackground(cc);
}




}

}
public static void main(String args[])
{
new offline();
}
}